mutation AddNewSuggestion @auth(level: USER) {
  suggestion_insert(data: {suggestedType: "New Feature", suggestionDetails: "Details of the new feature", suggestedById_expr: "auth.uid"})
}

query ListAllRoutes @auth(level: PUBLIC) {
  routes {
    id
    name
    description
    lengthKm
    estimatedTimeHours
  }
}

query ListPointOfInterests @auth(level: PUBLIC) {
  pointOfInterests {
    id
    name
    description
    latitude
    longitude
    type
    difficulty
  }
}

mutation UpdateSuggestionStatus($id: UUID!, $status: String!) @auth(level: USER) {
  suggestion_update(key: {id: $id}, data: {status: $status})
}