type User @table {
  displayName: String!
  createdAt: Timestamp!
  role: String!
  email: String
  photoUrl: String
}

type PointOfInterest @table {
  name: String!
  latitude: Float!
  longitude: Float!
  type: String!
  description: String
  imageUrl: String
  difficulty: String
}

type Route @table {
  name: String!
  description: String!
  lengthKm: Float!
  difficulty: String!
  elevationGainMeters: Int
  estimatedTimeHours: Float
  imageUrl: String
}

type RouteSegment @table {
  route: Route!
  latitude: Float!
  longitude: Float!
  order: Int!
}

type Suggestion @table {
  suggestedBy: User
  suggestedType: String!
  suggestionDetails: String!
  status: String
  adminNotes: String
}